pub mod handle_drop_entry_result;
pub mod handle_fetch_entry_result;
pub mod handle_get_authoring_entry_list_result;
pub mod handle_get_gossiping_entry_list_result;
pub mod handle_query_entry_result;
pub mod handle_send_direct_message_result;
pub mod handle_store_entry_aspect_result;
