agents = []

[[ui_bundles]]
id = "bundle1"
root_dir = "./example-config/example-static-site"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface-1"
bundle = "bundle1"
port = 3000
bind_address = "127.0.0.1"
reroute_to_root = true
dna_interface = "websocket interface"


[[interfaces]]
admin = true
id = "websocket interface"

    [interfaces.driver]
    port = 4000
    type = "websocket"
