######################################################################
# Automatically generated by qmake (3.0) Wed Jun 13 17:47:55 2018
######################################################################

TEMPLATE = app
TARGET = test_executable
INCLUDEPATH += .
LIBS += -L../../target/debug/ -lhc_dna_c_binding -ldl
QT += testlib

# Input
HEADERS += test.h
SOURCES += test.cpp

DESTDIR = ../../target/debug/c_binding_tests/hc_dna
OBJECTS_DIR = ../../target/debug/c_binding_tests/hc_dna/.obj
MOC_DIR = ../../target/debug/c_binding_tests/hc_dna/.moc
RCC_DIR = ../../target/debug/c_binding_tests/hc_dna/.rcc
UI_DIR = ../../target/debug/c_binding_tests/hc_dna/.ui
