[package]
name = "commit"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'

[workspace]
members = []

[dependencies]
serde="1"
serde_derive="1"
holochain_wasm_utils = { path = "../../../wasm_utils"}
holochain_core_types = { path = "../../../core_types"}
