[package]
name = "test-bridge-caller"
version = "0.0.2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'

[workspace]
members = []

[dependencies]
serde = "1.0"
serde_json = "1.0"
hdk = { path = "../../hdk-rust" }
serde_derive = "1.0"
