#!/bin/bash
docker login -u $DOCKER_USER -p $DOCKER_PASS

docker build -f Dockerfile.circle.base -t holochain/holochain-rust:circle-base .
docker push holochain/holochain-rust:circle-base

# docker build -f Dockerfile.circle.nixwarm -t holochain/holochain-rust:circle-nixwarm .
# docker build -f Dockerfile.circle.rustwarm -t holochain/holochain-rust:circle-rustwarm .
