# FROM holochain/holochain-rust:circle.13.warm.net-ipc
FROM holochain/holochain-rust:circle.02.warm.hdk

# the default command can be the unit tests, why not?
# if the build works properly this should be fast in incremental compilation
CMD nix-shell --run hc-test
