FROM holochain/holochain-rust:develop

RUN chown holochain:holochain /holochain
USER ${DOCKER_BUILD_USER}

COPY --chown=holochain . /holochain

WORKDIR /holochain

RUN make wasm_build

# warm cargo as much as possible
# we can't warm with a tarpaulin run as codecov requires runtime docker args
RUN cargo +${WASM_NIGHTLY} test
USER root

CMD cargo +${WASM_NIGHTLY} tarpaulin --all --out Xml
