FROM ubuntu

WORKDIR /root

RUN apt-get update && apt-get install libssl-dev pkg-config cmake zlib1g-dev curl qt5-default -y

RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-2018-06-01 -y

ENV PATH /root/.cargo/bin:$PATH

RUN rustc --version

RUN rustup component add rustfmt-preview

RUN cargo install clippy --version 0.0.206

COPY . /root/holochain
WORKDIR /root/holochain
RUN make test

CMD make test
