ARG DOCKER_BRANCH=develop
FROM holochain/holochain-rust:latest.${DOCKER_BRANCH}

RUN nix-shell --run 'cargo test -p hc --target-dir "$CARGO_TARGET_DIR"/cli-test'

ENV USER="$(id -u -n)"
ENV app_name=my_first_app
ENV zome_name=my_zome
RUN nix-shell --run hc-cli-install
RUN nix-shell --run 'command -v hc'
RUN nix-shell --run 'hc init "$TMP/$app_name"'
WORKDIR "$TMP/$app_name"
RUN nix-shell --run 'hc generate "zomes/$zome_name"'
ENV CARGO_TARGET_DIR="$CARGO_TARGET_DIR/cli/hc-test"
RUN echo "# $CARGO_TARGET_DIR"
RUN hc test
