FROM holochain/holochain-rust:minimal as build

RUN nix-env -iA holochain.sim2h_server
RUN nix-collect-garbage

# https://stackoverflow.com/questions/22713551/how-to-flatten-a-docker-image#22714556
FROM scratch
COPY --from=build / /
WORKDIR /holochain
ENV CARGO_HOME /holochain
ENV PATH "/holochain/.cargo/bin:${PATH}"

CMD sim2h_server -p 9000
