#!/usr/bin/env bash

if [ -n "$HOST_UID" ]; then
  OLDID=`id -u holochain`
  if [ "$OLDID" != "$HOST_UID" ]; then
    usermod -u "$HOST_UID" holochain
    groupmod -g "$HOST_UID" holochain
    usermod -g "$HOST_UID" holochain
    chown -R -h "$HOST_UID":"$HOST_UID" /home/holochain
  fi
fi

gosu holochain "$@"
