[package]
name = "test-proc-macro"
version = "0.0.18-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
hdk-proc-macros = { path = ".." }
hdk = { path = "../../hdk-rust" }

serde = "=1.0.89"
serde_derive = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
holochain_core_types_derive = { path = "../../core_types_derive" }
