[package]
name = "holochain_conductor_api_api"
version = "0.0.32-alpha2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
holochain_core_types = { path = "../core_types" }
holochain_wasm_utils = { path = "../wasm_utils" }
jsonrpc-core = { git = "https://github.com/holochain/jsonrpc", branch = "broadcaster-getter" }
jsonrpc-lite = "=0.5.0"
serde = { version = "=1.0.89", features = ["rc"] }
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
snowflake = "=1.3.0"