[package]
name = "holochain_walkman_types"
version = "0.0.42-alpha5"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_derive = "=1.0.89"
serde_millis = "=0.1.1"
serde_json = "=1.0.39"
url = "=2.1.0"
regex = "1.1.2"
